### ISSUE TITLE
Investigate allowing NULL collection dates (NA)

### ISSUE THREAD

**Issue by ktmeaton** [ktmeaton/ncov-recombinant#168]
> Generates error in `linelist`:  `ValueError: time data NA doesn't match format specified`
> Generates error in `plot`: `ValueError: NaTType does not support toordinal`

When integrating the pipeline into a sequencing run, the collection dates (`date`) are not always known.

The `date` column is used in the following pipeline rules:

- `linelist`
    - The `date` column is used to assign the first observed sequence of a lineage as the representative sequence for the `cluster_id`. 
    - If all sequences of a lineage are `NA`, potentially, could just pick the first one by sorting alphabetically.
- `plot`:
    - Almost all plots (except breakpoints) are a timeline with the X axis as collection dates. Potentially, all sequences with `NA` for dates could be dropped from plotting (and therefore from the reporting slides). There is already logic implemented to handle if all samples get plotted.

## Tasks

- [x] Handle `NA` dates in `linelist`
- [x] Handle `NA` dates in `lineages`
- [x] Handle `NA` dates in `parents`
- [x]  Handle `NA` dates in `plot`
- [x]  Handle `NA` dates in `report`

**Comment by ktmeaton** [comment]
I wonder if a workaround could be to temporarily set NA dates to TODAY at the beginning of the script, and then restore their values to NA at the end. This would be easier than writing custom logic and try-catch statements for every date-related function. But I'm not sure what the consequences are yet, so I will test it.

**Comment by ktmeaton** [comment]
`scripts/create_profiles.sh` doesn't do any validation of the date column. So no changes needed there.

**Comment by ktmeaton** [comment]
Shockingly, `linelist` needs no changes!
